### ISSUE TITLE
Adding Unicode Symbols to Macros

### ISSUE THREAD

**Issue by baudolino-seraph** [joshr120/open-deck#1]
In the GUI's Macro Setup, is it possible to add unicode symbols (e.g., em dash — , degree °, section §) as macro hotkeys? I have tried using the symbols themselves and the "Alt+" codes (e.g., ALT+0151 for "—") without success.

**Comment by joshr120** [comment]
I have found a workaround to make this work and have just pushed a new version of the pre-compiled GUI which should now work with "Alt+" codes in the following format:  e.g. for ° symbol use: "_alt+num 2+num 4+num 8_"

If you are not using the pre-complied .exe and running the source code you need to modify the keyboard library to get this to work. This can be done by finding the file "_canonical_names.py" and making the following changes:

Change:
 `'num 0': '0',  `  
to:
`'num 0': 'num 0',`

repeat for 0-9.

This allows the keyboard library to send numpad numbers (by default this library just replaces these with non-numpad number) required for alt+ codes.

Let me know if you have any more issues

**Comment by joshr120** [comment]
Fixed as per prev comment
