### ISSUE TITLE
Can you support more integrated devices?

### ISSUE THREAD

**Issue by lukedoomer** [joshr120/open-deck#3]
Your design is awesome. I hope you can support more common esp32-s3 devices. for example [wt32-sc01](https://www.openhasp.com/0.6.1/devices/wt32-sc01/) by wireless tag

**Comment by joshr120** [comment]
Not too sure what you mean by support more devices? This has a custom PCB specifically designed for the ESP8266 Wemos D1 V3 so you can't really just drop in a different microcontroller. The code would be fairly easy to get working on an ESP32 and if I do make an updated version it would probably use an ESP32
